// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEBProject.API.Data;

namespace WEBProject.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191026183242_AddedUsers")]
    partial class AddedUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("WEBProject.API.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Street");

                    b.Property<int>("ZipCode");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("WEBProject.API.Models.Amentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ApartmentId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.ToTable("Amentities");
                });

            modelBuilder.Entity("WEBProject.API.Models.Apartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("LocationId");

                    b.Property<int>("NumberOfGuests");

                    b.Property<int>("NumberOfRooms");

                    b.Property<string>("Photo");

                    b.Property<int>("PricePerNight");

                    b.Property<string>("Status");

                    b.Property<string>("TimeToArrive");

                    b.Property<string>("TimeToLeave");

                    b.Property<string>("Type");

                    b.Property<int?>("UserId");

                    b.Property<int?>("UserId1");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("WEBProject.API.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ApartmentId");

                    b.Property<int?>("AuthorId");

                    b.Property<int>("Grade");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("WEBProject.API.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AddressId");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("WEBProject.API.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AppartmentId");

                    b.Property<int?>("GuestId");

                    b.Property<int>("NumberOfNights");

                    b.Property<DateTime>("StartDate");

                    b.Property<string>("Status");

                    b.Property<int>("TotalPrice");

                    b.HasKey("Id");

                    b.HasIndex("AppartmentId");

                    b.HasIndex("GuestId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("WEBProject.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Gender");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Role");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WEBProject.API.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("WEBProject.API.Models.Amentity", b =>
                {
                    b.HasOne("WEBProject.API.Models.Apartment")
                        .WithMany("Amentities")
                        .HasForeignKey("ApartmentId");
                });

            modelBuilder.Entity("WEBProject.API.Models.Apartment", b =>
                {
                    b.HasOne("WEBProject.API.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("WEBProject.API.Models.User")
                        .WithMany("ApartmentsForRent")
                        .HasForeignKey("UserId");

                    b.HasOne("WEBProject.API.Models.User")
                        .WithMany("RentedApartments")
                        .HasForeignKey("UserId1");
                });

            modelBuilder.Entity("WEBProject.API.Models.Comment", b =>
                {
                    b.HasOne("WEBProject.API.Models.Apartment", "Apartment")
                        .WithMany("Comments")
                        .HasForeignKey("ApartmentId");

                    b.HasOne("WEBProject.API.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");
                });

            modelBuilder.Entity("WEBProject.API.Models.Location", b =>
                {
                    b.HasOne("WEBProject.API.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");
                });

            modelBuilder.Entity("WEBProject.API.Models.Reservation", b =>
                {
                    b.HasOne("WEBProject.API.Models.Apartment", "Appartment")
                        .WithMany("Reservations")
                        .HasForeignKey("AppartmentId");

                    b.HasOne("WEBProject.API.Models.User", "Guest")
                        .WithMany("Reservations")
                        .HasForeignKey("GuestId");
                });
#pragma warning restore 612, 618
        }
    }
}
